name: Run standalone benchmark scenario with multiple data rates
on:
  workflow_dispatch:
    inputs:
      input_machine_type:
        description: The machine type to use for each instance VM sending data to the aggregator.
        type: string
        default: e2-highcpu-8
        required: true
      input_machine_log_size:
        description: The size in bytes of each log message generated on the input VMs.
        type: string
        default: "1000"
        required: true
      input_machine_log_rate:
        description: The rate in logs per second to generate on the input VMs.
        type: string
        default: "20000"
        required: true
      gcp_project:
        description: The GCP project to run benchmarking in, i.e. where to create the VMs.
        type: string
        default: calyptia-benchmark
        required: true
      gcp_zone:
        description: The GCP zone to run benchmarking in, i.e. where to create the VMs.
        type: string
        default: us-central1-a
        required: true
      grafana_prometheus_url:
        description: The Grafana Cloud (or Prometheus remote write) endpoint for metrics.
        type: string
        default: prometheus-prod-10-prod-us-central-0.grafana.net
        required: true
      grafana_loki_url:
        description: The Grafana Cloud (or Loki) endpoint for logs.
        type: string
        default: logs-prod3.grafana.net
        required: true

jobs:
  run-gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up GCP authentication
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_BENCHMARKING_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Ensure defaults set up and usable
        run: |
          gcloud config set compute/zone ${{ inputs.gcp_zone }}
          gcloud config set project ${{ inputs.gcp_project }}
        shell: bash

      - name: Run benchmark setup script with parameters
        run: |
          ./examples/standalone-benchmarking/gcp.sh
        shell: bash
        env:
          MACHINE_TYPE: ${{ inputs.input_machine_type }}
          INPUT_LOG_SIZE: ${{ inputs.input_machine_log_size }}
          INPUT_LOG_RATE: ${{ inputs.input_machine_log_rate }}
          GCP_PROJECT: ${{ inputs.gcp_project }}
          GRAFANA_CLOUD_PROM_URL: ${{ inputs.grafana_prometheus_url }}
          GRAFANA_CLOUD_LOKI_URL: ${{ inputs.grafana_loki_url }}
          GRAFANA_CLOUD_PROM_USERNAME: ${{ secrets.GRAFANA_CLOUD_PROM_USERNAME }}
          GRAFANA_CLOUD_LOKI_USERNAME: ${{ secrets.GRAFANA_CLOUD_LOKI_USERNAME }}
          GRAFANA_CLOUD_APIKEY: ${{ secrets.GRAFANA_CLOUD_APIKEY }}
          GRAFANA_ANNOTATION_APIKEY: ${{ secrets.GRAFANA_CALYPTIA_BENCHMARKS_API_KEY }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: ./examples/standalone-benchmarking/output/
          if-no-files-found: error
